export const team = [
  {
    id: "01",
    name: "Emma Roys",
    profile_image: "/images/team/1.jpg",
    title: "Founder | CEO",
    bio: "I am a native Houstonian with a bachelor’s in Marketing from Baylor University, sic ‘em bears! I began my career as the Social Media Manager at Hennessey Performance, where I developed new strategies and grew their account from 300K to over 2.0M in two years! I found a deeper passion for social media and overall business growth, so I decided to use my social media knowledge to help other businesses succeed. This is why I started Roys Digital Media, the best comprehensive solution for all social media and marketing needs! I am overjoyed by the growth we have accomplished in the past two years and am so grateful and excited to see where my business will go in the future! Let’s create excitement together!",
  },
  {
    id: "02",
    name: "Alex Roys",
    profile_image: "/images/team/2.jpg",
    title: "Co-founder | COO ",
    bio: "I am from the great city of Houston and a proud Aggie! My wife, Emma, and I have been married for four years and couldn’t be happier! Together we started Roys Digital Media back in 2020 and have built the establishment we have today through hard work, dedication, and faith. I couldn’t be more proud of all we have accomplished together and the places we will go in the future. As COO of Roys Digital Media, I have great plans for the success of the company and all of its endeavors! We couldn’t be more excited to be working with such amazing clients and our wonderful dream team. We have no plans of slowing down and can only look forward as this company grows and becomes more successful. Let’s build something amazing!",
  },
  {
    id: "03",
    name: "Kaitlyn Burrow",
    profile_image: "/images/team/3.jpg",
    title: "Marketing Director",
    bio: "I am a native Houstonian but now live in Los Angeles, CA where I work as the Marketing Director for Roys Digital Media. I obtained my degree in Supply Chain Management from Baylor University in 2017, and decided to move abroad for a year after college! It was in Europe where I discovered the power of social media & marketing and began my career in the field. Beyond work, I spend my time at the beach, hiking, hanging with friends, or taking my dog to the park! It is an honor to be on the RDM team and I look forward to its very bright future!",
  },
  {
    id: "04",
    name: "Adde Terrando",
    profile_image: "/images/team/4.png",
    title: "Content Manager",
    bio: "Born and raised in Houston, TX, I made my way to the Hill Country to earn my Bachelor of Business Administration in Marketing from Texas State University, where I graduated magna cum laude. During college, I learned the ins and outs of social media and have continued to grow my passion for it within my career. I have always been creative and on the search of new outlets to express it. I taught myself graphic design and web design and am eager to learn more throughout my career at Roys Digital Media. I love good food & drinks, and in my free time I enjoy spending time with friends & family, and of course, cuddling my pups! I couldn’t be more excited to be a part of the RDM team!",
  },
  {
    id: "05",
    name: "Jillian Godfrey",
    profile_image: "/images/team/5.jpg",
    title: "Web Designer | Marketing Strategist",
    bio: "From the wonderfully diverse city of Houston, I have been surrounded by art and culture my entire life. I received my bachelor’s in Marketing - Advertising Strategy from Texas A&M University’s Mays Business School, where I graduated magna cum laude. I’ve had an eye for design since I was a kid and have been exploring and developing my creativity through a multitude of channels ever since. I began my career at Roys Digital Media in 2021 and have immersed myself in web design, graphic design, and brand development in my role here. I am passionate about my career for I get to use my creativity in new ways every day. I find beauty in marketing & advertising for its power to influence others through the communication of ideas, concepts, and beliefs. Let’s create!",
  },
  {
    id: "06",
    name: "Emily Kohring",
    profile_image: "/images/team/6.jpg",
    title: "Social Media Analyst | Event Strategist",
    bio: "I was born & raised in Kansas City but moved to Dallas to begin my career after graduating from the University of Arkansas. I studied Hospitality with a minor in Event Management, but am thrilled to have found myself in a creative marketing role. It has been a joy being one of Roys Digital Media’s Dallas-based employees where I am a social media manager, content creator, and event planner for our clients in the area. I am an iced coffee enthusiast, enjoy cycling, and have a miniature poodle named Beau who I am just a little obsessed with! Roys Digital Media has the brightest future ahead and I am honored to be a part of the journey to watch our clients flourish & grow!",
  },
  {
    id: "07",
    name: "Sarah Staffel",
    profile_image: "/images/team/7.png",
    title: "Social Media Analyst",
    bio: "Born in San Antonio and raised in Fort Worth, I followed a marketing career opportunity here in Houston, transferring from UT Austin to the University of Houston in 2020. With a degree in Communication and Media Studies, I found my true calling by combining my passion for art with the dynamic world of marketing. For me, marketing isn't just a job; it's a way to immerse myself in storytelling and craft compelling brand identities that deeply resonate with consumers.  I'm proud to be a part of the exceptional team at Roy's Digital Media, where I work as a social media manager, collaborating with a talented team who share my enthusiasm. Beyond work, I'm an avid painter, professional model, self-proclaimed espresso martini connoisseur, and proud dog mom to my rescue, Skipper.",
  },
  {
    id: "08",
    name: "Skylar Bean",
    profile_image: "/images/team/8.png",
    title: "Social Media Analyst",
    bio: "A Houston native through and through, I found my way back home after studying corporate communications with a minor in business at the University of Texas at Austin. Throughout my journey, I've always had a love for all things social media and marketing, and I'm thrilled to be in a position that allows me to continue pursuing that passion. Beyond my professional pursuits, I proudly embrace the title of 'dog mom' to Ricky, my Golden Retriever. Joining the Roys team fills me with excitement, and I can't wait to be a part of the bright future that lies ahead for Roys Digital Media!",
  },
  {
    id: "09",
    name: "Savannah Hennessey",
    profile_image: "/images/team/9.jpg",
    title: "Engagement Specialist",
    bio: "From Houston, Texas, I recently graduated from  Texas A&M University, where I majored in Communications with a minor in Entrepreneurship. I have a passion for people and am blessed to be immersed in this passion by cultivating communities and engagement for our clients. I have a love for dogs, reading, and traveling, amongst other things. I am beyond excited to be working with Roys Digital Media and enjoy seeing the impact of my work in our clients’ businesses.",
  },
  {
    id: "10",
    name: "Nate Roys",
    profile_image: "/images/team/10.jpg",
    title: "Director of Adorableness",
    bio: "Recently adopted by my loving parents, Emma and Alex, I spend my time around the office doing what a labor-doodle is best at, being ADORABLE! I love getting to be by my mom’s side every day as she is hard at work! I enjoy going on adventures with my parents, barking at squirrels, meeting new friends, and cuddling! In my role as Director of Adorableness at Roys Digital Media, I strive to bring cuteness, warmth, and love to all my team members throughout the week! My five-year goal is to master sneaking into the trash without Dad catching me and become the CAO - Chief Adorable Officer! WOOF!",
  },
];
